language: node_js
node_js:
  - 6.12.0
branches:
  only:
  - master
  - feature/travis
before_install:
  - sudo pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
  - export AWS_ACCESS_KEY_ID=$access_key_id
  - export AWS_SECRET_ACCESS_KEY=$secret_access_key
# env:
#   - AWS_ACCESS_KEY_ID=$access_key_id
#   - AWS_SECRET_ACCESS_KEY=$secret_access_key
install:
  - npm install
script:
  - aws s3 ls
