language: node_js
node_js:
  - 6.12.0
branches:
  only:
  - master
  - feature/travis
before_install:
  - sudo pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
  - export AWS_ACCESS_KEY_ID=$access_key_id
  - export AWS_SECRET_ACCESS_KEY=$secret_access_key
install:
  - npm install
script:
  - aws s3 ls
  - REACT_APP_API_URL=$REACT_APP_API_URL npm run build
  - aws s3 cp build s3://boriandmallorytravis/ --recursive --acl public-read
cache:
  directories:
    - "node_modules"
