language: node_js
node_js:
- 6.12
env:
  global:
    secure: o0zmDShWrZ0Cq8M+eqUGLX3skwJU7ILKRbBOThEnoIamv5NEbNaxuR0J5tpknB1rT87bALgC8zogAm1MOskm+6yS6eol1dJZ0mN1RzwvvEF+XPTr16XxBTPM0QIi9WJrRf3icXmUC73LJRc3Zri3dTan2nFfb86wOk2kkhpGBZfoxJBswnmUj43IurrFS0uM68UftIeM9WNu45CMHxD0kvwKiUfV8gTdVFiX9oqpuTeVWpJ3LcQw5wXzI33RVyRRMMTLMxIlNngGTpUNSQ581Dx+a3s6KtATLtQbAlEudvsadcAwrFzVugA9utu/E26vd+iJ+vNRY8H9rMot5ySTnojs05I5tESdhTcH+iWCJRo/1K5Z0Iz7Ztc8axlqTPO+yE1hSOmz0pjmzjCm+t4LUGA76QN82zYXP5FgiDZShrPoXl1zle3uGXzUkRjP9c7gZPfR6r6AHkd2gpULp8gvBNHMiU84hE2A4fc93eD6CNNGot0uxWoaKK3HfWpnHR9e+ut6ZLrlwlzp4vi/Hd6DuDSvzUnZYyrRjExlkxto/fGGhOdmfZ4sz0G/wwW+A3Dxv0M98q7pBIIbDopV+y2BI6KIFIHmNZi83qWkNy3Nw/UvzfRn9XZu232Ol5IlmKkfwZbDO4Mcd7jJe3W4DpvQNew3u9mUEuMOpFgiEafC1FY=
deploy:
  provider: s3
  access_key_id: AKIAJJ3FJ6AINLK3C4LQ
  secret_access_key:
    secure: on6GlN5pSVeVs/n32eNM3TuZZNFCW3oA87jSdRbejz+S4PnKn4qHCoX/A0Lpbtohnw3/0My7DyOPBOen/D1aUuJb6PHRxg196hyr1TKN6bnJreLiW7YbSLhWJMjef07n6LvMc9+J3QhvcC1hbl0pIz4bXmlj9DQ+cXp2BdZbNKcC11q8ARTR58H7QQ72Iy4Sot9pm+PvuVTfGrkC7h2ACZBoBv/cjtUAycqIxe4Oybg9J34lheLlOSBm1skoCfzhfb3YXkNa/09evl/NNt5sPWZsT1P6PJ3kewH63t1Q4cYewAe36BJHI0VhYfa+W78kpgmbtReUeSEVOLMLCTfEPosBDHbjLskD9ZVO5XiaD2cHjVLWCOxI8J+yMECynDdT1nlKNRh9+INSKR9u8+i4AjaxpVrI56AkdoP6P8vdvbkymiTtf7/WprgekN+tH697DbJ/e2kQW5WtJ2bFb+ftVugduTuzvDcULs+oO1mIrXLz7UaOci8Ag/aZVb+TTu/GfUCCX0toqgR5sHN4ejKovrBgER3f8nkae5uuS4cMIQs41e/HJVvxx6rMWg7MFIXiwc1SUaVqq3ychtJUOeUt1XXlT/7OEptR2k/gIC4O9L5dx9aw0OH1+lGbDB1ZorYQ+ILWgH9v304L9NhMdSJBgcJpD1saDJM2j5TL0+Fu75k=
  bucket: boriandmallorytest.com
  local-dir: "./build/*"
  acl: public_read
  on:
    repo: borikanes/wedding-ui
