language: node_js
node_js:
  - 6.12
branches:
  only:
  - master
  - feature/travis
before_install:
  - sudo pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
env:
  - AWS_ACCESS_KEY_ID=$access_key_id
  - AWS_SECRET_ACCESS_KEY=$secret_access_key
script:
  - aws s3 ls
